# Generated by Django 5.2.8 on 2025-11-06 14:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroupTemplate',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tokens', models.CharField(blank=True, help_text='Comma-separated list of tokens (e.g., SKU, VARIETYNAME)', max_length=500)),
                ('tasks', wagtail.fields.StreamField([('task', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Task title (can use tokens like {SKU})', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated labels (e.g., sow, plant)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('labels', 1)]], {})})),
            ],
            options={
                'verbose_name': 'Task Group Template',
            },
            bases=('wagtailcore.page',),
        ),
    ]
