# Generated by Django 5.2.8 on 2026-02-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("todosync", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropTask",
            fields=[
                (
                    "baseparenttask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="todosync.baseparenttask",
                    ),
                ),
                ("sku", models.CharField(help_text="Product SKU", max_length=100)),
                ("variety_name", models.CharField(help_text="Variety name", max_length=200)),
                ("bed", models.CharField(blank=True, help_text="Bed location for this crop", max_length=100)),
            ],
            options={
                "verbose_name": "Crop Task",
                "verbose_name_plural": "Crop Tasks",
            },
            bases=("todosync.baseparenttask",),
        ),
        migrations.CreateModel(
            name="BiennialCropTask",
            fields=[
                (
                    "croptask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.croptask",
                    ),
                ),
                (
                    "bed_second_year",
                    models.CharField(blank=True, help_text="Bed location for second year growth", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Biennial Crop Task",
                "verbose_name_plural": "Biennial Crop Tasks",
            },
            bases=("tasks.croptask",),
        ),
    ]
