# Generated by Django 5.2.8 on 2026-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="croptask",
            name="crop",
            field=models.CharField(blank=True, help_text="Crop name (e.g., Tomato, Lettuce)", max_length=200),
        ),
    ]
