# Generated by Django 5.2.8 on 2026-02-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croptaskgrouptemplate',
            options={'verbose_name': 'Crop Template', 'verbose_name_plural': 'Crop Templates'},
        ),
    ]
