# Generated by Django 5.2.8 on 2025-11-06 14:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgrouptemplate',
            name='tasks',
            field=wagtail.fields.StreamField([('task', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Task title (can use tokens like {SKU})', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated labels (e.g., sow, plant)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtask title (can use tokens)', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated labels', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('labels', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'help_text': 'Subtasks for this task', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('labels', 1), ('subtasks', 5)]], {})}),
        ),
    ]
