# Generated by Django 5.2.8 on 2026-02-10 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_croptask_crop"),
        ("todosync", "0003_remove_basetaskgrouptemplate_task_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropTaskGroupTemplate",
            fields=[
                (
                    "basetaskgrouptemplate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="todosync.basetaskgrouptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Task Group Template",
                "verbose_name_plural": "Crop Task Group Templates",
            },
            bases=("todosync.basetaskgrouptemplate",),
        ),
    ]
