# Generated by Django 5.2.8 on 2025-11-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskplannersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskPlannerSettings',
        ),
    ]
