# Generated by Django 5.2.8 on 2025-11-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_taskplannersettings'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgrouptemplate',
            name='tokens',
        ),
        migrations.CreateModel(
            name='TaskPlannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.CharField(blank=True, help_text='Comma-separated list of tokens (e.g., SKU, VARIETYNAME)', max_length=500)),
                ('parent_task_title', models.CharField(blank=True, help_text='Title template for parent task (can use tokens like {SKU}). If empty, uses the template page title.', max_length=200)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Task Planner Settings',
            },
        ),
    ]
