# Generated by Django 5.2.8 on 2025-11-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_taskgrouptemplate_tokens_taskplannersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgrouptemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Description for this template (can use tokens like {SKU}). This will be appended to the site-wide description.'),
        ),
        migrations.AddField(
            model_name='taskplannersettings',
            name='description',
            field=models.TextField(blank=True, help_text='Description template for parent task (can use tokens like {SKU}). This will be prepended to the template description.'),
        ),
    ]
