# Generated by Django 5.2.8 on 2025-11-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskgrouptemplate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskplannersettings',
            name='todoist_project_id',
            field=models.CharField(blank=True, help_text='Todoist project ID where tasks should be created. Leave empty to create tasks in the inbox.', max_length=100),
        ),
    ]
