# Generated by Django 5.2.8 on 2025-11-12 09:44

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskplannersettings_todoist_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelSectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Label to match (e.g., 'harvest', 'plant')", max_length=100)),
                ('destination_section_id', models.CharField(help_text='Todoist section ID where completed tasks with this label should be moved', max_length=100)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_section_rules', to='tasks.taskplannersettings')),
            ],
            options={
                'verbose_name': 'Label Section Rule',
                'verbose_name_plural': 'Label Section Rules',
            },
        ),
    ]
