# Generated by Django 5.2.8 on 2025-11-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_labelsectionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskplannersettings',
            name='source_section_id',
            field=models.CharField(blank=True, help_text='Todoist section ID to monitor for completed tasks. Only completed tasks from this section will be moved based on label rules.', max_length=100),
        ),
    ]
