# Generated by Django 5.2.8 on 2025-11-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskplannersettings_source_section_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskplannersettings',
            name='source_section_id',
        ),
        migrations.AddField(
            model_name='labelsectionrule',
            name='source_section_id',
            field=models.CharField(blank=True, help_text='Todoist section ID to monitor for completed tasks with this label', max_length=100),
        ),
    ]
