# Generated by Django 5.2.8 on 2026-02-09 11:50

from django.db import migrations


def migrate_settings(apps, schema_editor):
    """Copy TaskPlannerSettings to TaskSyncSettings"""
    # Get old and new models
    TaskPlannerSettings = apps.get_model('tasks', 'TaskPlannerSettings')
    TaskSyncSettings = apps.get_model('todosync', 'TaskSyncSettings')

    # Copy each TaskPlannerSettings record to TaskSyncSettings
    for old_settings in TaskPlannerSettings.objects.all():
        TaskSyncSettings.objects.create(
            site_id=old_settings.site_id,
            tokens=old_settings.tokens,
            parent_task_title=old_settings.parent_task_title,
            description=old_settings.description,
            todoist_project_id=old_settings.todoist_project_id,
        )


def migrate_label_rules(apps, schema_editor):
    """Copy LabelSectionRule to LabelActionRule"""
    # Get old and new models
    LabelSectionRule = apps.get_model('tasks', 'LabelSectionRule')
    LabelActionRule = apps.get_model('todosync', 'LabelActionRule')
    TaskSyncSettings = apps.get_model('todosync', 'TaskSyncSettings')

    # Copy each LabelSectionRule to LabelActionRule
    for old_rule in LabelSectionRule.objects.all():
        # Find the corresponding new settings
        try:
            new_settings = TaskSyncSettings.objects.get(site_id=old_rule.settings.site_id)
            LabelActionRule.objects.create(
                settings_id=new_settings.id,
                source_section_id=old_rule.source_section_id,
                label=old_rule.label,
                destination_section_id=old_rule.destination_section_id,
            )
        except TaskSyncSettings.DoesNotExist:
            # Skip if the corresponding settings don't exist
            pass


def migrate_page_content_type(apps, schema_editor):
    """Update TaskGroupTemplate pages to BaseTaskGroupTemplate"""
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Page = apps.get_model('wagtailcore', 'Page')

    # Get old and new content types
    try:
        old_ct = ContentType.objects.get(app_label='tasks', model='taskgrouptemplate')
        new_ct = ContentType.objects.get(app_label='todosync', model='basetaskgrouptemplate')

        # Update all pages with old content type to new content type
        Page.objects.filter(content_type=old_ct).update(content_type=new_ct)

        print(f"Migrated {Page.objects.filter(content_type=new_ct).count()} pages to BaseTaskGroupTemplate")
    except ContentType.DoesNotExist:
        # If content types don't exist, skip
        pass


def reverse_migration(apps, schema_editor):
    """Reverse migration - copy data back"""
    # This is a simplified reverse - in production you might want more careful handling
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_taskplannersettings_source_section_id_and_more'),
        ('todosync', '0001_initial'),
        ('contenttypes', '__latest__'),
        ('wagtailcore', '__latest__'),
    ]

    operations = [
        migrations.RunPython(migrate_settings, reverse_migration),
        migrations.RunPython(migrate_label_rules, reverse_migration),
        migrations.RunPython(migrate_page_content_type, reverse_migration),
    ]
