# Generated by Django 5.2.8 on 2026-02-09 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_migrate_to_todosync'),
        ('todosync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropTaskTemplate',
            fields=[
                ('basetaskgrouptemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todosync.basetaskgrouptemplate')),
                ('bed', models.CharField(blank=True, help_text='Bed location for this crop', max_length=100)),
            ],
            options={
                'verbose_name': 'Crop Task Template',
                'verbose_name_plural': 'Crop Task Templates',
            },
            bases=('todosync.basetaskgrouptemplate',),
        ),
        migrations.RemoveField(
            model_name='taskgrouptemplate',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='taskplannersettings',
            name='site',
        ),
        migrations.CreateModel(
            name='BiennialCropTaskTemplate',
            fields=[
                ('croptasktemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.croptasktemplate')),
                ('bed_second_year', models.CharField(blank=True, help_text='Bed location for second year growth', max_length=100)),
            ],
            options={
                'verbose_name': 'Biennial Crop Task Template',
                'verbose_name_plural': 'Biennial Crop Task Templates',
            },
            bases=('tasks.croptasktemplate',),
        ),
        migrations.DeleteModel(
            name='LabelSectionRule',
        ),
        migrations.DeleteModel(
            name='TaskGroupTemplate',
        ),
        migrations.DeleteModel(
            name='TaskPlannerSettings',
        ),
    ]
