# Generated by Django 5.2.8 on 2026-02-09 16:57

from django.db import migrations


def fix_page_content_types(apps, schema_editor):
    """Update pages with stale content types to BaseTaskGroupTemplate."""
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Page = apps.get_model('wagtailcore', 'Page')

    try:
        base_ct = ContentType.objects.get(app_label='todosync', model='basetaskgrouptemplate')
    except ContentType.DoesNotExist:
        # Fresh database — no content types or pages to migrate
        return

    # Fix any pages pointing to old content types
    stale_cts = ContentType.objects.filter(
        app_label='tasks',
        model__in=['croptasktemplate', 'biennialcroptasktemplate', 'taskgrouptemplate'],
    )
    for ct in stale_cts:
        updated = Page.objects.filter(content_type=ct).update(content_type=base_ct)
        if updated:
            print(f"  Updated {updated} page(s) from {ct.app_label}.{ct.model} to todosync.basetaskgrouptemplate")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_croptask_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RunPython(fix_page_content_types, migrations.RunPython.noop),
    ]
